name: Addon Release

on:
  push:
    branches: ["main", "Development"]
    tags: v*
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/addon-code-check.yml
    secrets: inherit

  release:
    needs: "build"
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.10
      - name: Build Zip
        run: |
          python zipfiles.py
      - name: Check Tag Type
        id: tagtype
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+[ab][0-9]+$ ]]; then
              echo ::set-output name=type::pre
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=type::release
          fi
      - name: Publish PreRelease
        if: steps.tagtype.outputs.type == 'pre'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "duplicate-finder-addon.zip"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
      - name: Publish Release
        if: steps.tagtype.outputs.type == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "duplicate-finder-addon.zip"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
